<?php

namespace AppBundle\Repository;

/**
 * BirthdayBoyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BirthdayBoyRepository extends \Doctrine\ORM\EntityRepository
{
}
