<?php

namespace AppBundle\Repository;

/**
 * SpectaclePeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpectaclePeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
