<?php

namespace AppBundle\Repository;

use AppBundle\Entity\SpectaclePeriod;

/**
 * UserApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotChecked()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AppBundle:UserApplication u
                WHERE u.checkedByAdmin = FALSE
                ORDER BY u.spectacleDate DESC
            ')->getResult();
    }

    public function findChecked()
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AppBundle:UserApplication u
                WHERE u.checkedByAdmin = TRUE
                ORDER BY u.spectacleDate DESC
            ')->getResult();
    }

    public function findAllFor(SpectaclePeriod $spectaclePeriod)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AppBundle:UserApplication u
                WHERE u.spectaclePeriod = :spectacle
                ORDER BY u.spectacleDate DESC
            ')->setParameter('spectacle', $spectaclePeriod)->getResult();
    }

    public function findCheckedFor(SpectaclePeriod $spectaclePeriod)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AppBundle:UserApplication u
                WHERE u.checkedByAdmin = TRUE AND u.spectaclePeriod = :spectacle
                ORDER BY u.spectacleDate DESC
            ')->setParameter('spectacle', $spectaclePeriod)->getResult();
    }

    public function findNotCheckedFor(SpectaclePeriod $spectaclePeriod)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT u
                FROM AppBundle:UserApplication u
                WHERE u.checkedByAdmin = FALSE AND u.spectaclePeriod = :spectacle
                ORDER BY u.spectacleDate DESC
            ')->setParameter('spectacle', $spectaclePeriod)->getResult();
    }
}
